openapi: 3.0.0
info:
  version: 1
  title: User Service
  license:
    name: MIT License
    url: https://choosealicense.com/licenses/mit/
  description: |
    Rest service for manage user account, register and login.

    ## URI BASE
    
    The URI is formated by the host and the version.
    
    `{protocol}://{host}/api/v1`

    ## Data Type
    
    The data type used by the API is JSON. 
    
    ### Data field allowed:
     * Integer
     * Double
     * String
     * Array
     * Object
     * Date ISO 8601
    
    ## HATEOAS
    
    Some endpoints migth implement HATEOAS in the body response identified by `*_uri`.

    ## Authorization
    
    The authorization method is based in one time generation token which must be sent in the header by the key `app_key`

    ## HTTP Methods
    
    | Method | CRUD |
    | ------------- | ------------- |
    | HEAD | Head info|
    | GET  | Read |
    | POST  | Create  |
    | PATCH  | Update/Modify  |
    | PUT  | Update/Replace  |
    | DELETE  | Delete |
    
    ## HTTP CODE
    | Code | Description |
    | ------------- | ------------- |
    | 200 | OK |
    | 201  | Created |
    | 400  | Bad Request  |
    | 401  | Unauthorized4  |
    | 403  | Forbidden  |
    | 404  | Not Found |
    | 408  | Timeout |
    | 500  | Server Error |
    | 501  | Not Implemented |
    | 503  | Service Unavailable |

     
servers:
  - url: http://localhost:5000/api/v1
    description: Local for testing
  - url: https://sandbox.users.creations.com/api/v1
    description: Sandox for testing
    

paths:
  /auth:
    post:
      summary: Create a account
      tags:
        - Auth
      parameters:
        - $ref: '#/components/schemas/HeaderAppCode'
        - $ref: '#/components/schemas/HeaderAppId'
        - $ref: '#/components/schemas/HeaderIpRequest'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserForm'
      responses:
        "202":
          description: New method of login registered
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/Login'
        "201":
          description: User created
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/Login'
        "200":
          description: User already has account
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/Login'
        "400":
          description: Error on data
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "403":
          description: Error on singup
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /auth/session:
    post:
      summary: Create a session
      tags:
        - Auth
      parameters:
        - $ref: '#/components/schemas/HeaderAppCode'
        - $ref: '#/components/schemas/HeaderAppId'
        - $ref: '#/components/schemas/HeaderIpRequest'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserLogin'
      responses:
        "201":
          description: Session created
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/Login'
        "200":
          description: Session returned
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/Login'
        "400":
          description: Error on data
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "403":
          description: Error on signin
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    get:
      summary: Get info session
      tags:
        - Auth
      parameters:
        - $ref: '#/components/schemas/HeaderAppCode'
        - $ref: '#/components/schemas/HeaderAppId'
        - $ref: '#/components/schemas/HeaderIpRequest'
        - $ref: '#/components/schemas/HeaderToken'
      responses:
        "200":
          description: Session returned
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/Login'
        "400":
          description: Error on data
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "403":
          description: Error on signin
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
         
        



components:
  schemas:
    HeaderIpRequest:
      in: header
      name: request-ip
      description: Ip from request
      type: string
      required: true
    HeaderAppCode:
      in: header
      name: app-code
      description: Code app on system
      type: string
      required: true
    HeaderAppId:
      in: header
      name: app-id
      type: string
      format: uuid
      required: true
    HeaderToken:
      in: header
      name: token
      description: Token of login
      type: string
      required: true
    UserId:
      type: string
      description: Object Id
      required: true
    UserIdObject:
      type: object
      properties:
        user_id:
          $ref: "#/components/schemas/UserId" 
    UserEmail:
      type: object
      properties:
        email: 
          type: string
          description: User email
          required: true
    UserUsername:
      type: object
      properties:
        username:
          type: string
          description: User username (Not required for Facebook nor Google)
          required: false
    UserIndetifier:
      type: object
      properties:
        identifier:
          type: string
          description: Username or Email of user
          required: true
    UserBase:
      type: object
      properties:
        type: 
          type: string
          description: Type of signup
          required: true
        hash:
          type: string
          description: Password encrypted or id_hash from google/facebook 
          required: true
    UserForm:
      allOf:
        - $ref: "#/components/schemas/UserEmail" 
        - $ref: "#/components/schemas/UserUsername" 
        - $ref: "#/components/schemas/UserBase"

    UserLogin:
      allOf:
        - $ref: "#/components/schemas/UserIndetifier" 
        - $ref: "#/components/schemas/UserBase"
    
    UserObject:
      type: object
      properties:
        state:
          type: string
          description: State of user
          required: true
    User:
      allOf:
        - $ref: "#/components/schemas/UserIdObject"
        - $ref: "#/components/schemas/UserForm" 
        - $ref: "#/components/schemas/UserObject" 
    Login:
      type: object
      properties:
        username:
          type: string
          required: true
        token:
          type: string
          required: true
    Error:
      type: object
      properties:
        code:
          type: string
          description: Error code
        message:
          type: string
          description: Error description
      required:
        - code
        - message  

